<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>UtilityBilling.Application</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="FluentValidation" Version="11.11.0" />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
      <PackageReference Include="Mapster" Version="7.4.0" />
      <PackageReference Include="Mapster.DependencyInjection" Version="1.0.1" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\UtilityBilling.Contracts\UtilityBilling.Contracts.csproj" />
      <ProjectReference Include="..\UtilityBilling.Infrastructure\UtilityBilling.Infrastructure.csproj" />
    </ItemGroup>

</Project>
