<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>UtilityBilling.Api</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MediatR" Version="12.4.1" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.1" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.1" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.3">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.1" />
        <PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.10.0" />
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.10.0" />
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.10.0" />
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.10.1" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.10.0" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\UtilityBilling.Application\UtilityBilling.Application.csproj" />
    </ItemGroup>

</Project>
