// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UtilityBilling.Infrastructure.Database;

#nullable disable

namespace UtilityBilling.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UtilityBilling.Domain.UtilityBillPeriod.UtilityBill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<int>("MeasurementUnitType")
                        .HasColumnType("integer");

                    b.Property<decimal>("Usage")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UtilityBillPeriodId")
                        .HasColumnType("uuid");

                    b.Property<int>("UtilityBillType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UtilityBillPeriodId");

                    b.ToTable("UtilityBills");

                    b.HasData(
                        new
                        {
                            Id = new Guid("997f4444-f8f3-4ca0-9b2e-ea7464938f65"),
                            Cost = 32.44m,
                            MeasurementUnitType = 0,
                            Usage = 25.52m,
                            UtilityBillPeriodId = new Guid("813ae334-2637-4212-b0de-100cf7faa6ab"),
                            UtilityBillType = 0
                        },
                        new
                        {
                            Id = new Guid("e67328ae-bcdb-4f40-b5f2-bfaf2a584736"),
                            Cost = 17.29m,
                            MeasurementUnitType = 1,
                            Usage = 7.50m,
                            UtilityBillPeriodId = new Guid("813ae334-2637-4212-b0de-100cf7faa6ab"),
                            UtilityBillType = 1
                        },
                        new
                        {
                            Id = new Guid("a1c25f4f-1a01-44f2-bb10-8519607ee466"),
                            Cost = 12.25m,
                            MeasurementUnitType = 0,
                            Usage = 3.22m,
                            UtilityBillPeriodId = new Guid("813ae334-2637-4212-b0de-100cf7faa6ab"),
                            UtilityBillType = 2
                        });
                });

            modelBuilder.Entity("UtilityBilling.Domain.UtilityBillPeriod.UtilityBillPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("UtilityBillPeriods");

                    b.HasData(
                        new
                        {
                            Id = new Guid("813ae334-2637-4212-b0de-100cf7faa6ab"),
                            EndDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "December 2024",
                            StartDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            UserId = new Guid("99d5d2cf-93e1-4300-ac09-39849738d744")
                        },
                        new
                        {
                            Id = new Guid("60a42c2d-c5e9-4692-8746-dee5831a16e6"),
                            EndDate = new DateTime(2025, 1, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "January 2025",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            UserId = new Guid("99d5d2cf-93e1-4300-ac09-39849738d744")
                        },
                        new
                        {
                            Id = new Guid("e3a31ffb-ff65-4fcd-a652-e241e372e757"),
                            EndDate = new DateTime(2025, 2, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "February 2025",
                            StartDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            UserId = new Guid("99d5d2cf-93e1-4300-ac09-39849738d744")
                        },
                        new
                        {
                            Id = new Guid("a2b48d07-98bc-48fa-893b-290d3f068a39"),
                            EndDate = new DateTime(2025, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "March 2025",
                            StartDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            UserId = new Guid("99d5d2cf-93e1-4300-ac09-39849738d744")
                        },
                        new
                        {
                            Id = new Guid("29a69221-03a7-41fe-9c10-4645a7db10e7"),
                            EndDate = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "April 2025",
                            StartDate = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            UserId = new Guid("99d5d2cf-93e1-4300-ac09-39849738d744")
                        });
                });

            modelBuilder.Entity("UtilityBilling.Domain.UtilityBillPeriod.UtilityBill", b =>
                {
                    b.HasOne("UtilityBilling.Domain.UtilityBillPeriod.UtilityBillPeriod", "UtilityBillPeriod")
                        .WithMany("UtilityBills")
                        .HasForeignKey("UtilityBillPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UtilityBillPeriod");
                });

            modelBuilder.Entity("UtilityBilling.Domain.UtilityBillPeriod.UtilityBillPeriod", b =>
                {
                    b.Navigation("UtilityBills");
                });
#pragma warning restore 612, 618
        }
    }
}
